### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by agarrharr** [SimonBiggs/jekyll-google-drive#1]
I was just checking out this repo and it seems like a really cool project. I was just wondering if you could add a little bit of documentation to help explain what it is and maybe help people learn how to use it.

For my church website, everything is just stored in the git repo (except for sermon audio on Amazon AWS), but I've been thinking lately about how to allow other people to edit the site. Using Google Drive might be the perfect way to do it.

**Comment by SimonBiggs** [comment]
Hi Adam,

We've decided to upload our sermons to archive.org. The free hosting is
helpful.

The meat of the project is in the following file:
https://github.com/SimonBiggs/jekyll-google-drive/blob/gh-pages/_includes/_google_sheet_pull.html

And this file allows users to edit content on the site by double clicking
on the editable div:
https://github.com/SimonBiggs/jekyll-google-drive/blob/gh-pages/_includes/_google_sheet_editor.html

The part that pulls from the Google sheet is the following lines of code:
<script src="https://spreadsheets.google.com/feeds/cells/{{
site.google_sheet_id }}/{{ site.google_sheet_layout_page_number
}}/public/values?alt=json-in-script&callback=load_layout_data"></script>

<script src="https://spreadsheets.google.com/feeds/cells/{{
site.google_sheet_id }}/{{ site.google_sheet_contents_page_number
}}/public/values?alt=json-in-script&callback=load_content_data"></script>

Hopefully that gives you a good start. Please let me know further if I can
be of help.

Cheers,
Simon

**Comment by agarrharr** [comment]
Yeah, I saw that with archive.org. That looks like a great option.

So do they edit the content in Google Drive or directly on the website? And if it's on the website, how do they begin editing. Is there an edit button? How does it look like a normal website for some users and an editable site for some users?

**Comment by agarrharr** [comment]
Also, is it loading the data (via JavaScript) from Google Drive everytime someone visits a page? Or is it building the entire static site once per edit?

And are you hosting on Github Pages?

**Comment by SimonBiggs** [comment]
Here is a demo of it live:
http://churchsitedemo.simonbiggs.net

Try double clicking on some divs once the page has had time to load.

**Comment by SimonBiggs** [comment]
And yes, it pulls the content of the editable divs via JavaScript. It only
pulls it on the first page load. Subsequent clicks don't actually reload
the page, instead just redraw the relevant sections using the already
loaded data.

**Comment by agarrharr** [comment]
Ok, thanks. I might try to do something like this on my own site.

**Comment by SimonBiggs** [comment]
I was thinking of actually making an Angular2 component that pulls and is
editable from Google Drive. Call this a "ContentComponent". Have it store
the results in an IndexedDB database using DexieJS. On initial load it
would used the cached content, after the component was loaded it would then
pull from Google Drive to update the IndexedDB data.

The next thought was then to make another component that would pull its
layout from Google Drive, call this LayoutComponent. The LayoutComponent
would be based off of a basic grid, and it would be nice if there was an
interactive way to edit the layout also.

If this was produced in a way that was decoupled from any project it might
be quite useful for all sorts of websites.

**Comment by agarrharr** [comment]
Yeah. It would also be nice if it was decoupled from any framework like Angular. I was thinking of just building a vanilla js library to pull data from Google Drive, store it in Local Storage, and then it would have functions to pull it out of Local Storage.

I'm just not sure how I would convert from markdown to html on the fly.

I also probably wouldn't have the website go into editable mode just by double clicking. It seems convenient for editors, but other users might double-click unintentionally.

**Comment by SimonBiggs** [comment]
I agree with all your points. Makes sense.

**Comment by SimonBiggs** [comment]
I would prefer IndexedDB over localstorage. Best not to have the whole page block while loading from localstorage.
